import { categories, products, money } from './products.js';

const keys = { cart: 'renu-cart', wishlist: 'renu-wishlist' };
const read = (key) => JSON.parse(localStorage.getItem(key) || '[]');
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
export const getCart = () => read(keys.cart);
export const getWishlist = () => read(keys.wishlist);
export const cartCount = () => getCart().reduce((total, item) => total + item.quantity, 0);
export const wishlistCount = () => getWishlist().length;
export const syncCounts = () => { document.querySelectorAll('[data-cart-count]').forEach((el) => { el.textContent = cartCount(); el.hidden = cartCount() === 0; }); document.querySelectorAll('[data-wishlist-count]').forEach((el) => { el.textContent = wishlistCount(); el.hidden = wishlistCount() === 0; }); };
export const toggleWishlist = (id) => { const wishlist = getWishlist(); const next = wishlist.includes(Number(id)) ? wishlist.filter((item) => item !== Number(id)) : [...wishlist, Number(id)]; write(keys.wishlist, next); syncCounts(); return next.includes(Number(id)); };
export const addToCart = (id, quantity = 1, size = '', color = '') => { const cart = getCart(); const existing = cart.find((item) => item.id === Number(id) && item.size === size && item.color === color); if (existing) existing.quantity += quantity; else cart.push({ id: Number(id), quantity, size, color }); write(keys.cart, cart); syncCounts(); return cart; };
export const removeFromCart = (id, size = '', color = '') => { write(keys.cart, getCart().filter((item) => !(item.id === Number(id) && item.size === size && item.color === color))); syncCounts(); };
export const updateCartQuantity = (id, quantity, size = '', color = '') => { const cart = getCart(); const item = cart.find((entry) => entry.id === Number(id) && entry.size === size && entry.color === color); if (item) item.quantity = Math.max(1, quantity); write(keys.cart, cart); syncCounts(); };

const icon = (name) => ({ search: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>', user: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="8" r="3.5"></circle><path d="M5 20c.8-3.3 3.1-5 7-5s6.2 1.7 7 5"></path></svg>', heart: '♡', bag: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 8h14l-1 12H6L5 8Z"></path><path d="M9 9V6a3 3 0 0 1 6 0v3"></path></svg>' }[name]);

function headerTemplate() { return `<div class="announcement">Free shipping on orders above ₹999 &nbsp; • &nbsp; Easy returns &nbsp; • &nbsp; Shop Renu Super Shopie</div><header class="site-header"><div class="section-shell header-inner"><button class="icon-button menu-toggle" aria-label="Open menu" data-menu-toggle>☰</button><nav class="main-nav"><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="shop.html?category=Sarees">Sarees</a><a href="shop.html?category=Readymade">Readymade</a><a href="shop.html?category=Jewellery">Jewellery</a><a href="shop.html?sort=newest">New arrivals</a><a href="about.html">About</a></nav><a class="brand" href="index.html"><strong>RENU</strong><small>SUPER SHOPIE</small></a><div class="utility"><a class="icon-button utility-link" href="shop.html" aria-label="Search">${icon('search')}</a><a class="icon-button utility-link" href="wishlist.html" aria-label="Wishlist">${icon('heart')}<span class="count" data-wishlist-count hidden>0</span></a><a class="icon-button utility-link" href="contact.html" aria-label="Account">${icon('user')}</a><a class="icon-button" href="cart.html" aria-label="Shopping bag">${icon('bag')}<span class="count" data-cart-count hidden>0</span></a></div></div></header><div class="mobile-drawer" data-mobile-drawer><a href="index.html">Home</a><a href="shop.html">Shop all</a><a href="shop.html?category=Sarees">Sarees</a><a href="shop.html?category=Readymade">Readymade</a><a href="shop.html?category=Jewellery">Jewellery</a><a href="wishlist.html">Wishlist</a></div>`; }
function footerTemplate() { return `<footer class="site-footer"><div class="section-shell"><div class="footer-grid"><div class="footer-brand"><strong>RENU</strong><p>A considered edit of Indian fashion and lifestyle, selected to stay with you beyond the occasion.</p></div><div class="footer-column"><h3>Shop</h3><a href="shop.html?category=Sarees">Sarees</a><a href="shop.html?category=Readymade">Readymade</a><a href="shop.html?category=Kurtis">Kurtis</a><a href="shop.html?category=Dresses">Dresses</a><a href="shop.html?category=Jewellery">Jewellery</a></div><div class="footer-column"><h3>Customer care</h3><a href="contact.html">Contact us</a><a href="contact.html">Shipping</a><a href="contact.html">Returns</a><a href="contact.html">FAQs</a></div><div class="footer-column"><h3>About</h3><a href="about.html">Our story</a><a href="contact.html">Privacy policy</a><a href="contact.html">Terms & conditions</a></div><div class="footer-column"><h3>Follow us</h3><a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram</a><a href="https://facebook.com" target="_blank" rel="noreferrer">Facebook</a><a href="https://wa.me/919999999999" target="_blank" rel="noreferrer">WhatsApp</a></div></div><div class="footer-bottom">© 2026 Renu Super Shopie. All Rights Reserved.</div></div></footer>`; }
function categoryArt(category) { const type = category.toLowerCase(); return `<div class="category-art ${type}"></div>`; }
export function productVisual(product, extra = '') { return `<div class="product-visual ${product.visual} ${extra}" aria-label="Abstract ${product.name} placeholder" role="img"></div>`; }
export function productCard(product) { const wished = getWishlist().includes(product.id); const discount = product.oldPrice ? Math.round((1 - product.price / product.oldPrice) * 100) : 0; return `<article class="product-card"><a href="product.html?id=${product.id}">${productVisual(product)}${discount ? `<span class="product-badge">-${discount}%</span>` : ''}</a><button class="wishlist-button ${wished ? 'active' : ''}" aria-label="${wished ? 'Remove from wishlist' : 'Add to wishlist'}" data-wishlist="${product.id}">${wished ? '♥' : '♡'}</button><div class="product-info"><a href="product.html?id=${product.id}"><h3>${product.name}</h3></a><p class="product-category">${product.category}</p><div class="price">${money(product.price)}${product.oldPrice ? `<span class="old-price">${money(product.oldPrice)}</span>` : ''}</div><div class="card-actions"><button class="button button-primary" data-add="${product.id}">Add to cart</button><a class="button quick-view" href="product.html?id=${product.id}">View</a></div></div></article>`; }
function bindGlobal() { document.querySelectorAll('[data-wishlist]').forEach((button) => button.addEventListener('click', () => { const active = toggleWishlist(button.dataset.wishlist); button.classList.toggle('active', active); button.textContent = active ? '♥' : '♡'; button.setAttribute('aria-label', active ? 'Remove from wishlist' : 'Add to wishlist'); })); document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', () => { addToCart(button.dataset.add); button.textContent = 'Added'; setTimeout(() => { button.textContent = 'Add to cart'; }, 1200); })); }
function initHome() { const categoryGrid = document.querySelector('#category-grid'); if (categoryGrid) categoryGrid.innerHTML = categories.map((category) => `<a class="category-card" href="shop.html?category=${category}">${categoryArt(category)}<h3>${category}</h3></a>`).join(''); const arrivals = document.querySelector('#new-arrivals'); if (arrivals) arrivals.innerHTML = products.slice(0, 8).map(productCard).join(''); document.querySelector('[data-newsletter]')?.addEventListener('submit', (event) => { event.preventDefault(); const form = event.currentTarget; form.querySelector('.form-message').textContent = 'Thank you. You are on the list.'; form.reset(); }); bindGlobal(); }

document.querySelector('#site-header').innerHTML = headerTemplate(); document.querySelector('#site-footer').innerHTML = footerTemplate(); syncCounts(); document.querySelector('[data-menu-toggle]')?.addEventListener('click', () => document.querySelector('[data-mobile-drawer]').classList.toggle('open')); window.addEventListener('scroll', () => document.querySelector('.site-header')?.classList.toggle('scrolled', window.scrollY > 10)); if (document.body.dataset.page === 'home') initHome();
