import { products } from './products.js';
import { productCard } from './main.js';

const params = new URLSearchParams(location.search);
let category = params.get('category') || 'All';
let sort = params.get('sort') || 'newest';
let query = params.get('q') || '';
const grid = document.querySelector('[data-shop-grid]');
const resultCount = document.querySelector('[data-result-count]');
const render = () => { let list = category === 'All' ? [...products] : products.filter((product) => product.category === category); if (query) list = list.filter((product) => `${product.name} ${product.category}`.toLowerCase().includes(query.toLowerCase())); if (sort === 'low') list.sort((a, b) => a.price - b.price); if (sort === 'high') list.sort((a, b) => b.price - a.price); if (sort === 'best') list.sort((a, b) => b.stock - a.stock); grid.innerHTML = list.length ? list.map(productCard).join('') : '<p class="empty-state">No products found. <button class="text-link" data-clear-search>Clear search</button></p>'; resultCount.textContent = `${list.length} pieces`; document.querySelectorAll('[data-category]').forEach((button) => button.classList.toggle('active', button.dataset.category === category)); document.querySelector('[data-sort]').value = sort; const searchInput = document.querySelector('[data-search]'); if (searchInput) searchInput.value = query; document.querySelector('[data-clear-search]')?.addEventListener('click', () => { query = ''; render(); }); document.querySelectorAll('[data-wishlist]').forEach((button) => button.addEventListener('click', () => import('./main.js').then(({ toggleWishlist }) => { const active = toggleWishlist(button.dataset.wishlist); button.classList.toggle('active', active); button.textContent = active ? '♥' : '♡'; }))); document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', () => import('./main.js').then(({ addToCart }) => { addToCart(button.dataset.add); button.textContent = 'Added'; }))); };
document.querySelectorAll('[data-category]').forEach((button) => button.addEventListener('click', () => { category = button.dataset.category; render(); })); document.querySelector('[data-sort]').addEventListener('change', (event) => { sort = event.target.value; render(); }); document.querySelector('[data-search]')?.addEventListener('input', (event) => { query = event.target.value.trim(); render(); }); render();
